name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [ api, worker, listener ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase repository
        id: repo_lower
        run: |
          REPO_LOWER="${{ github.repository }}"
          REPO_LOWER="${REPO_LOWER,,}"
          echo "REPO_LOWER=$REPO_LOWER"
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT  # GITHUB_OUTPUT 用于 outputs


      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.repo_lower.outputs.repo_lower }}-${{ matrix.service }}:latest
            ${{ env.REGISTRY }}/${{ steps.repo_lower.outputs.repo_lower }}-${{ matrix.service }}:${{ github.sha }}