name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [api, worker, listener]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase repository
        run: |
          # 将 github.repository 转为小写
          echo "REPO_LOWER=${{ github.repository }}" >> $GITHUB_ENV
          REPO_LOWER="${REPO_LOWER,,}"
          echo "REPO_LOWER=$REPO_LOWER" >> $GITHUB_ENV


      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}-${{ matrix.service }}:latest
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER}}-${{ matrix.service }}:${{ github.sha }}